/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiWatchStreamRouteImport } from './routes/api/watch/stream'
import { Route as ApiWatchSuggestRouteImport } from './routes/api/watch/suggest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchStreamRoute = ApiWatchStreamRouteImport.update({
  id: '/api/watch/stream',
  path: '/api/watch/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchSuggestRoute = ApiWatchSuggestRouteImport.update({
  id: '/api/watch/suggest',
  path: '/api/watch/suggest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/watch/stream': typeof ApiWatchStreamRoute
  '/api/watch/suggest': typeof ApiWatchSuggestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/watch/stream': typeof ApiWatchStreamRoute
  '/api/watch/suggest': typeof ApiWatchSuggestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/watch/stream': typeof ApiWatchStreamRoute
  '/api/watch/suggest': typeof ApiWatchSuggestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/stream'
    | '/api/watch/stream'
    | '/api/watch/suggest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/stream'
    | '/api/watch/stream'
    | '/api/watch/suggest'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/stream'
    | '/api/watch/stream'
    | '/api/watch/suggest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiWatchStreamRoute: typeof ApiWatchStreamRoute
  ApiWatchSuggestRoute: typeof ApiWatchSuggestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/stream': {
      id: '/api/watch/stream'
      path: '/api/watch/stream'
      fullPath: '/api/watch/stream'
      preLoaderRoute: typeof ApiWatchStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/suggest': {
      id: '/api/watch/suggest'
      path: '/api/watch/suggest'
      fullPath: '/api/watch/suggest'
      preLoaderRoute: typeof ApiWatchSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiWatchStreamRoute: ApiWatchStreamRoute,
  ApiWatchSuggestRoute: ApiWatchSuggestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
